# Generated by Django 4.0.5 on 2022-07-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dangky', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='send_gmail',
        ),
    ]
