# Generated by Django 4.0.5 on 2022-07-06 03:30

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trangtt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='noidung',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='tieude',
            field=models.CharField(max_length=100),
        ),
    ]
